spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/sparkstory
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        fotmat_sql: true



